services:
  - type: web
    name: image-to-video-server
    env: docker
    plan: free
    region: singapore
    repo: https://github.com/nguyenhungdungspecial/image-to-video-server
    branch: main
    dockerfilePath: ./Dockerfile
